routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/reportOne', function () {
                $t=\Illuminate\Support\Facades\DB::table('morris_chart')->select('device','geekbench')->get();
    $record= array($t);
  //  dd($record);
   // $record = $this->convertToString($r);
    return view('report.demo1',['record'=>$record]);
})->name('reportOne');

Route::get('/reportTwo', function () {
    return view('report.demo2');
})->name('reportTwo');

Route::get('/reportThree', function () {
    return view('report.demo3');
})->name('reportThree');

Route::get('/reportFour', function () {
    return view('report.demo4');
})->name('reportFour');


Route::namespace('Backend')->group(function (){
    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::resource('admin', 'AdminController', ['only' => [
        'index', 'create' , 'store', 'edit', 'update'
    ]]);
    Route::get('admin/list','AdminController@ajaxList')->name('admin.list');
    Route::post('admin/status','AdminController@changeStatus')->name('admin.status');

    Route::resource('sales_report','SalesReportController', ['only' => [
        'index', 'create' , 'store', 'edit', 'update'
    ]]);

    Route::get('sales/report','SalesReportController@getChartReport')->name('sales.report');
    Route::get('brand/{bid}/products','SalesReportController@bandByChartReport')->name('brand.products');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Backend/AdminController.php
<?php

namespace App\Http\Controllers\Backend;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Session;
use Yajra\DataTables\DataTables;

class AdminController extends Controller
{
    public function index()
    {
        $data['title']='List of admin';
        return view('backend.admin.index',$data);
    }
    public function ajaxList()
    {
        $admins=User::all();

        return Datatables::of($admins)->addColumn('status', function($admins) {
            if($admins->status=='Active'){
                return '<button data-id="'.$admins->id.'" data-status="'.$admins->status.'"   class="status-modal btn btn-success"> <i class="fa fa-check-square-o"></i>Active  </button>';
               }
            else{
                return '<button data-id="'.$admins->id.'" data-status="'.$admins->status.'"    class="status-modal btn btn-danger"><i class="fa fa-times"></i> Inactive  </button>';
            }

        })->addColumn('actions',function ($admins){
            return '<a href="'.route("admin.edit",$admins->id).'" class="btn btn-primary"><i class="fa fa-edit"></i></a>';
        })->rawColumns(['Status'=>'status','actions'=>'actions'])->setRowClass(function ($admins) {
            return 'itemcat'.$admins->id;
        })->make(true);
    }
    public function create()
    {
        $data['title']='Create admin';
        return view('backend.admin.create',$data);
    }
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'email'=>'required|email',
            'password'=>'required|confirmed',
        ]);
        $user=new User();
        $user->name=$request->name;
        $user->address=$request->address;
        $user->phone=$request->phone;
        $user->email=$request->email;
        $user->password=bcrypt($request->password);
        $user->save();
        Session::flash('message', 'Admin successfully created.');
        return redirect()->back();
    }
    public function edit($id)
    {
        $data['title']='Edit admin';
        $data['admin']=User::findOrFail($id);
        return view('backend.admin.edit',$data);
    }
    public function update(Request $request,$id)
    {
        $request->validate([
            'name'=>'required',
            'email'=>'required|email',
        ]);
        $user=User::findOrFail($id);
        $user->name=$request->name;
        $user->address=$request->address;
        $user->phone=$request->phone;
        $user->email=$request->email;
        $user->save();
        Session::flash('message', 'Admin successfully updated.');
        return redirect()->back();
    }

    public function changeStatus(Request $req)
    {
        $status= User::find($req->id);
        if($req->status=='Active')
        {
            $status->status='Inactive';
            $message="danger";
        }
        else{
            $status->status='Active';
            $message="success";
        }
        $status->save();
        return response ()->json ( ['status'=>$status,'message'=>$message] );
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;

class DashboardController extends Controller
{
    public function index()
    {
        $data['totalCompany']=DB::table('company')->count();
        $data['totalProducts']=DB::table('products')->count();
        $data['totalSales']=DB::table('sales_reports')->sum('netSalesAmount');
        $data['totalprofit']=DB::table('sales_reports')->sum('grossProfitAmount');
        return view('backend/dashboard',$data);
    }
}

app/Http/Controllers/Backend/SalesReportController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use App\SalesReport;
use Session;
class SalesReportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $all=new SalesReport();
        if($request->has('company_id') && $request->company_id != null)
        {
            $all=$all->where('company_id',$request->company_id);
        }
        if($request->has('brand_id') && $request->brand_id != null)
        {
            $all=$all->where('brand_id',$request->brand_id);
        }
        if($request->has('product_id') && $request->product_id != null)
        {
            $all=$all->where('product_id',$request->product_id);
        }
        $data['all']=$all->get();
        $data['companies']=DB::table('company')->pluck('name','id');
        $data['brands']=DB::table('brand')->pluck('name','id');
        $data['products']=DB::table('products')->pluck('name','id');
        return view('backend.salesReports.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companylist=DB::table('company')->pluck('name','id');
        $brandlist=DB::table('brand')->pluck('name','id');
        $productlist=DB::table('products')->pluck('name','id');
       return view('backend.salesReports.create',['companylist'=>$companylist,
           'brandlist'=>$brandlist,
           'productlist'=>$productlist]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
       //dd($request->all());
        $salesReportsave=SalesReport::insert(['company_id'=>$request->company_id,
            'brand_id'=>$request->brand_id,
            'product_id'=>$request->product_id,
            'unit'=>$request->unit,
            'netSalesAmount'=>$request->netSalesAmount,
            'costOfSalesAmount'=>$request->costOfSalesAmount,
            'grossProfitAmount'=>$request->grossProfitAmount]);
        Session::flash('message', 'Sales Report successfully created.');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function getChartReport()
    {
        /*
         * SELECT sum(unit),sum(grossProfitAmount), brand_id
            FROM sales_reports
            GROUP BY brand_id;
         * */
//         $t=SalesReport::select('brand_id','unit','grossProfitAmount','brand.name as brand')
         /*$t=DB::table('sales_reports')->select('sales_reports.brand_id','sales_reports.unit','sales_reports.grossProfitAmount')
//             ->join('brand', 'brand.id', '=', 'sales_reports.brand_id')
             ->where('company_id',2)
             ->groupBy('brand_id')
             ->sum('sales_reports.grossProfitAmount');
//             ->get();
//             ->count();*/
        $t=DB::select("SELECT sum(unit) as unit,sum(grossProfitAmount) as grossProfitAmount, brand_id, brand.name as brand FROM sales_reports JOIN brand ON sales_reports.brand_id=brand.id GROUP BY brand_id,brand");
//         dd($t);
        $record= array($t);
       return view('backend.salesReports.salesReportChart',['record'=>$record]);
    }

    public function bandByChartReport($id)
    {

          $t=SalesReport::select('unit','grossProfitAmount','products.name as pname')
            ->join('products', 'products.id', '=', 'sales_reports.product_id')->where('sales_reports.brand_id',$id)->get();
       // $t=DB::select("SELECT sum(unit) as unit,sum(grossProfitAmount) as grossProfitAmount, brand_id, brand.name as brand FROM sales_reports JOIN brand ON sales_reports.brand_id=brand.id GROUP BY brand_id,brand");
//         dd($t);
        $record= array($t);
        return view('backend.salesReports.chartBrandByProduct',['record'=>$record]);
    }
}

resources/views/layouts/backend/_footer.blade.php
<div class="text-center">
   <?php echo date('Y'); ?> &copy;  {{ config('app.name') }}.
    <a href="#" class="go-top">
        <i class="fa fa-angle-up"></i>
    </a>
</div>

resources/views/layouts/backend/_head.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="csrf-token" content="{{ csrf_token() }}">
<meta name="description" content="">
<meta name="author" content="Mosaddek">
<meta name="keyword" content="ADN Digital">
<link rel="shortcut icon" href="#">

<title>{{ config('app.name') }}</title>

<!-- Bootstrap core CSS -->
<link href="{!! asset('css/bootstrap.min.css') !!}" rel="stylesheet">
<link href="{!! asset('css/bootstrap-reset.css') !!}" rel="stylesheet">
<!--external css-->
<link href="{!! asset('assets/font-awesome/css/font-awesome.css') !!}" rel="stylesheet" />
<link href="{!! asset('assets/toastr-master/toastr.css') !!}" rel="stylesheet" type="text/css" />


<!-- Custom styles for this template -->

<link href="{!! asset('css/style.css') !!}" rel="stylesheet">
<link href="{!! asset('css/style-responsive.css') !!}" rel="stylesheet" />
<link href="{!! asset('css/custom.css') !!}" rel="stylesheet">

@stack('css')
<style>
    /*footer fixed design*/
    .site-footer {
        position: fixed;
        width: 100%;
        bottom: 0px;
    }
</style>
<!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
<!--[if lt IE 9]>
<script src="{!! asset('js/html5shiv.js') !!}"></script>
<script src="{!! asset('js/respond.min.js') !!}"></script>
<![endif]-->
<!-- Imoportant JS -->
<script src="{!! asset('js/jquery.js') !!}"></script>
<script src="{!! asset('js/bootstrap.min.js') !!}"></script>
<!-- Imoportant JS -->

resources/views/layouts/backend/_header.blade.php
<div class="sidebar-toggle-box">
    <i class="fa fa-bars"></i>
</div>
<!--logo start-->
<a href="{!! route('dashboard') !!}" class="logo">{{ config('app.name') }}</a>
<!--logo end-->
<div class="nav notify-row" id="top_menu">
    <!--  notification start -->
    <ul class="nav top-menu">
        <!-- settings start -->
        {{--<li class="dropdown">--}}
            {{--<a data-toggle="dropdown" class="dropdown-toggle" href="#">--}}
                {{--<i class="fa fa-tasks"></i>--}}
                {{--<span class="badge bg-success">6</span>--}}
            {{--</a>--}}
            {{--<ul class="dropdown-menu extended tasks-bar">--}}
                {{--<div class="notify-arrow notify-arrow-green"></div>--}}
                {{--<li>--}}
                    {{--<p class="green">You have 6 pending tasks</p>--}}
                {{--</li>--}}
                {{--<li>--}}
                    {{--<a href="#">--}}
                        {{--<div class="task-info">--}}
                            {{--<div class="desc">Dashboard v1.3</div>--}}
                            {{--<div class="percent">40%</div>--}}
                        {{--</div>--}}
                        {{--<div class="progress progress-striped">--}}
                            {{--<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">--}}
                                {{--<span class="sr-only">40% Complete (success)</span>--}}
                            {{--</div>--}}
                        {{--</div>--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li>--}}
                    {{--<a href="#">--}}
                        {{--<div class="task-info">--}}
                            {{--<div class="desc">Database Update</div>--}}
                            {{--<div class="percent">60%</div>--}}
                        {{--</div>--}}
                        {{--<div class="progress progress-striped">--}}
                            {{--<div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">--}}
                                {{--<span class="sr-only">60% Complete (warning)</span>--}}
                            {{--</div>--}}
                        {{--</div>--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li>--}}
                    {{--<a href="#">--}}
                        {{--<div class="task-info">--}}
                            {{--<div class="desc">Iphone Development</div>--}}
                            {{--<div class="percent">87%</div>--}}
                        {{--</div>--}}
                        {{--<div class="progress progress-striped">--}}
                            {{--<div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 87%">--}}
                                {{--<span class="sr-only">87% Complete</span>--}}
                            {{--</div>--}}
                        {{--</div>--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li>--}}
                    {{--<a href="#">--}}
                        {{--<div class="task-info">--}}
                            {{--<div class="desc">Mobile App</div>--}}
                            {{--<div class="percent">33%</div>--}}
                        {{--</div>--}}
                        {{--<div class="progress progress-striped">--}}
                            {{--<div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 33%">--}}
                                {{--<span class="sr-only">33% Complete (danger)</span>--}}
                            {{--</div>--}}
                        {{--</div>--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li>--}}
                    {{--<a href="#">--}}
                        {{--<div class="task-info">--}}
                            {{--<div class="desc">Dashboard v1.3</div>--}}
                            {{--<div class="percent">45%</div>--}}
                        {{--</div>--}}
                        {{--<div class="progress progress-striped active">--}}
                            {{--<div class="progress-bar"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 45%">--}}
                                {{--<span class="sr-only">45% Complete</span>--}}
                            {{--</div>--}}
                        {{--</div>--}}

                    {{--</a>--}}
                {{--</li>--}}
                {{--<li class="external">--}}
                    {{--<a href="#">See All Tasks</a>--}}
                {{--</li>--}}
            {{--</ul>--}}
        {{--</li>--}}
        <!-- settings end -->
        <!-- inbox dropdown start-->
        {{--<li id="header_inbox_bar" class="dropdown">--}}
            {{--<a data-toggle="dropdown" class="dropdown-toggle" href="#">--}}
                {{--<i class="fa fa-envelope-o"></i>--}}
                {{--<span class="badge bg-important">5</span>--}}
            {{--</a>--}}
            {{--<ul class="dropdown-menu extended inbox">--}}
                {{--<div class="notify-arrow notify-arrow-red"></div>--}}
                {{--<li>--}}
                    {{--<p class="red">You have 5 new messages</p>--}}
                {{--</li>--}}
                {{--<li>--}}
                    {{--<a href="#">--}}
                        {{--<span class="photo"><img alt="avatar" src="{!! asset('img/avatar-mini.jpg') !!}" ></span>--}}
                        {{--<span class="subject">--}}
                                    {{--<span class="from">Jonathan Smith</span>--}}
                                    {{--<span class="time">Just now</span>--}}
                                    {{--</span>--}}
                        {{--<span class="message">--}}
                                        {{--Hello, this is an example msg.--}}
                                    {{--</span>--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li>--}}
                    {{--<a href="#">--}}
                        {{--<span class="photo"><img alt="avatar" src="{!! asset('img/avatar-mini2.jpg') !!}"></span>--}}
                        {{--<span class="subject">--}}
                                    {{--<span class="from">Jhon Doe</span>--}}
                                    {{--<span class="time">10 mins</span>--}}
                                    {{--</span>--}}
                        {{--<span class="message">--}}
                                     {{--Hi, Jhon Doe Bhai how are you ?--}}
                                    {{--</span>--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li>--}}
                    {{--<a href="#">--}}
                        {{--<span class="photo"><img alt="avatar" src="{!! asset('img/avatar-mini3.jpg') !!}"></span>--}}
                        {{--<span class="subject">--}}
                                    {{--<span class="from">Jason Stathum</span>--}}
                                    {{--<span class="time">3 hrs</span>--}}
                                    {{--</span>--}}
                        {{--<span class="message">--}}
                                        {{--This is awesome dashboard.--}}
                                    {{--</span>--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li>--}}
                    {{--<a href="#">--}}
                        {{--<span class="photo"><img alt="avatar" src="{!! asset('img/avatar-mini4.jpg') !!}"></span>--}}
                        {{--<span class="subject">--}}
                                    {{--<span class="from">Jondi Rose</span>--}}
                                    {{--<span class="time">Just now</span>--}}
                                    {{--</span>--}}
                        {{--<span class="message">--}}
                                        {{--Hello, this is metrolab--}}
                                    {{--</span>--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li>--}}
                    {{--<a href="#">See all messages</a>--}}
                {{--</li>--}}
            {{--</ul>--}}
        {{--</li>--}}
        <!-- inbox dropdown end -->
        <!-- notification dropdown start-->
        {{--<li id="header_notification_bar" class="dropdown">--}}
            {{--<a data-toggle="dropdown" class="dropdown-toggle" href="#">--}}

                {{--<i class="fa fa-bell-o"></i>--}}
                {{--<span class="badge bg-warning">7</span>--}}
            {{--</a>--}}
            {{--<ul class="dropdown-menu extended notification">--}}
                {{--<div class="notify-arrow notify-arrow-yellow"></div>--}}
                {{--<li>--}}
                    {{--<p class="yellow">You have 7 new notifications</p>--}}
                {{--</li>--}}
                {{--<li>--}}
                    {{--<a href="#">--}}
                        {{--<span class="label label-danger"><i class="fa fa-bolt"></i></span>--}}
                        {{--Server #3 overloaded.--}}
                        {{--<span class="small italic">34 mins</span>--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li>--}}
                    {{--<a href="#">--}}
                        {{--<span class="label label-warning"><i class="fa fa-bell"></i></span>--}}
                        {{--Server #10 not respoding.--}}
                        {{--<span class="small italic">1 Hours</span>--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li>--}}
                    {{--<a href="#">--}}
                        {{--<span class="label label-danger"><i class="fa fa-bolt"></i></span>--}}
                        {{--Database overloaded 24%.--}}
                        {{--<span class="small italic">4 hrs</span>--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li>--}}
                    {{--<a href="#">--}}
                        {{--<span class="label label-success"><i class="fa fa-plus"></i></span>--}}
                        {{--New user registered.--}}
                        {{--<span class="small italic">Just now</span>--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li>--}}
                    {{--<a href="#">--}}
                        {{--<span class="label label-info"><i class="fa fa-bullhorn"></i></span>--}}
                        {{--Application error.--}}
                        {{--<span class="small italic">10 mins</span>--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li>--}}
                    {{--<a href="#">See all notifications</a>--}}
                {{--</li>--}}
            {{--</ul>--}}
        {{--</li>--}}
        <!-- notification dropdown end -->
    </ul>
    <!--  notification end -->
</div>
<div class="top-nav ">
    <!--search & user info start-->
    <ul class="nav pull-right top-menu">
        <li>
            <input type="text" class="form-control search" placeholder="Search">
        </li>
        <!-- user login dropdown start-->
        <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <img alt="" src="{!! asset('img/avatar1_small.jpg') !!}">
                <span class="username">{{ config('app.name') }}</span>
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu extended logout">
                <div class="log-arrow-up"></div>
                <li><a href="#"><i class=" fa fa-suitcase"></i>Profile</a></li>
                <li><a href="#"><i class="fa fa-cog"></i> Settings</a></li>
                <li><a href="#"><i class="fa fa-bell-o"></i> Notification</a></li>
                <li>
                <a class="dropdown-item" href="{{ route('logout') }}"
                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                    <i class="fa fa-key"></i>  {{ __('Logout') }}
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
                </li>
            </ul>
        </li>
        <li class="sb-toggle-right">
            {{--<i class="fa  fa-align-right"></i>--}}
        </li>
        <!-- user login dropdown end -->
    </ul>
    <!--search & user info end-->
</div>

resources/views/layouts/backend/_messages.blade.php
<message>
    {{--set some message after action--}}
    @if (\Session::has('message'))
        <script>
            toastr.success('{!! \Session::get("message") !!}');
        </script>
    @elseif(\Session::has('warning'))
        <script>
            toastr.warning('{!! \Session::get("warning") !!}');
        </script>
    @elseif(\Session::has('info'))
        <script>
            toastr.info('{!! \Session::get("info") !!}');
        </script>
    @elseif(\Session::has('danger'))
        <script>
            toastr.error('{!! \Session::get("danger") !!}');
        </script>
    @endif
</message>

resources/views/layouts/backend/_nav.blade.php
<div id="sidebar"  class="nav-collapse ">
    <!-- sidebar menu start-->
    <ul class="sidebar-menu" id="nav-accordion">
        <li>
            <a class="{{ request()->segment(1) == 'dashboard' ? 'active' : null }}" href="{!! route('dashboard') !!}">
                <i class="fa fa-dashboard"></i>
                <span>Dashboard</span>
            </a>
        </li>

        <li class="sub-menu">
            <a href="javascript:;" class="{{ request()->segment(1) == 'admin' ? 'active' : null }}" >
                <i class="fa fa-user"></i>
                <span>Admins</span>
            </a>
            <ul class="sub">
                <li class="{{ request()->segment(2) == '' ? 'active' : null }}"><a href="{{ route('admin.index') }}">Lists</a></li>
                <li class="{{ request()->segment(2) == 'create' ? 'active' : null }}"><a href="{{ route('admin.create') }}">Create</a></li>
            </ul>
        </li>
        <li class="sub-menu">
            <a href="javascript:;" class="{{ request()->segment(1) == 'reportOne' || request()->segment(1) == 'reportTwo' || request()->segment(1) == 'reportThree' || request()->segment(1) == 'reportFour' ? 'active' : null }}">
                <i class=" fa fa-bar-chart-o"></i>
                <span>Report</span>
            </a>
            <ul class="sub">
                <li class="{{ request()->segment(1) == 'reportOne' ? 'active' : null }}" ><a href="{!! route('reportOne') !!}">Report Demo 1</a></li>
                <li class="{{ request()->segment(1) == 'reportTwo' ? 'active' : null }}" ><a href="{!! route('reportTwo') !!}">Report Demo 2</a></li>
                <li class="{{ request()->segment(1) == 'reportThree' ? 'active' : null }}" ><a href="{!! route('reportThree') !!}">Report Demo 3</a></li>
                <li class="{{ request()->segment(1) == 'reportFour' ? 'active' : null }}" ><a href="{!! route('reportFour') !!}">Report Demo 4</a></li>
            </ul>
        </li>
        <li class="sub-menu">
            <a href="javascript:;" class="{{ request()->segment(1) == 'sales_report' ? 'active' : null }}">
                <i class=" fa fa-bar-chart-o"></i>
                <span>Sales Report</span>
            </a>
            <ul class="sub">
                <li  class="{{ request()->segment(2) == 'create' ? 'active' : null }}"><a  href="{{ route('sales_report.create') }}">Create</a></li>
                <li class="{{ request()->segment(2) == '' ? 'active' : null }}"><a  href="{!! route('sales_report.index') !!}">Lists</a></li>
                <li class="{{request()->segment(1) == '' ? 'active' : null }}"><a  href="{!! route('sales.report') !!}">Sales Chart</a></li>

            </ul>
        </li>
    </ul>
    <!-- sidebar menu end-->
</div>

resources/views/layouts/backend/_scripts.blade.php
<!-- js placed at the end of the document so the pages load faster -->
<script class="include" type="text/javascript" src="{!! asset('js/jquery.dcjqaccordion.2.7.js') !!}"></script>
<script src="{!! asset('js/jquery.scrollTo.min.js') !!}"></script>

<script src="{!! asset('assets/toastr-master/toastr.js') !!}"></script>
<!--toastr js-->
@include('layouts.backend._messages')

<!--common script for all pages-->
<script src="{!! asset('js/common-scripts.js') !!}"></script>
<script src="{{ asset('js/custom.js') }}"></script>


@stack('js')

resources/views/layouts/backend/_validationErrorMessages.blade.php
@if($errors->any())
    <ul class="alert alert-danger fade in animated slideInRight alert-dismissable">
        <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close"><i  class="fa fa-times" aria-hidden="true"></i></a>
        @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
@endif

resources/views/layouts/backend/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    @include('layouts.backend._head')

</head>

<body>

<section id="container">
    <!--header start-->
    <header class="header white-bg">
        @include('layouts.backend._header')
    </header>
    <!--header end-->
    <!--sidebar start-->
    <aside>
        @include('layouts.backend._nav')
    </aside>
    <!--sidebar end-->
    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
            @include('layouts.backend._messages')
            @yield('content')
        </section>
    </section>
    <!--main content end-->


    <!--footer start-->
    <footer class="site-footer">
        @include('layouts.backend._footer')
    </footer>
    <!--footer end-->
</section>
@include('layouts.backend._scripts')
</body>
</html>